export type Command = {
  name: string
  args: string
  desc: string
  category: string
  access: string
}

export const CATEGORIES = [
  "All", "General", "Fun", "Moderation", "Aboveall", "Owner", "Panels",
] as const

type Row = [name: string, args: string, desc: string]
const group = (category: Command["category"], access: Command["access"], rows: Row[]): Command[] =>
  rows.map(([name, args, desc]) => ({ name, args, desc, category, access }))

export const COMMANDS: Command[] = [
  ...group("General", "Anyone", [
    ["help", "None", "browse commands by category."], ["ping", "None", "show websocket latency."], ["roles", "None", "list server roles and member counts."], ["whois", "[user]", "show member details, roles, access, and activity."], ["profile", "[user]", "show a member's avatar, banner, and account dates."], ["avatar", "[user]", "show a user's full-size avatar."], ["serverinfo", "None", "show server statistics."], ["bosses", "None", "list the server's owners."], ["whitelisted", "None", "show owner, aboveall, and whitelist rosters."], ["afk", "[reason]", "set an afk status until your next message."], ["timedisconnect", "<duration|cancel>", "schedule or cancel your voice disconnect; accepts 6h20m1s."], ["ticket", "[reason]", "open a private ticket, or post the ticket panel."], ["ticket close", "None", "request closure of your ticket."], ["ask", "<question>", "ask the bot about commands. alias: ai."], ["support", "None", "get the support server link."], ["oneandonly", "None", "show the bot creator."],
  ]),
  ...group("Fun", "Anyone", [
    ["gaymeter", "[user]", "show a deterministic rating. alias: howgay."], ["simprate", "[user]", "show a deterministic rating. alias: simp."], ["iqmeter", "[user]", "show a deterministic score. alias: iq."], ["howhot", "[user]", "show a deterministic rating. alias: hot."], ["braincells", "[user]", "show a deterministic count."], ["pp", "[user]", "show a deterministic size joke."], ["vibecheck", "[user]", "show a deterministic vibe rating."], ["ship", "<user1> <user2>", "show a compatibility rating. alias: ratelove."], ["rate", "<thing>", "rate text from 0 to 100."], ["8ball", "<question>", "return a random answer."], ["coinflip", "None", "flip a coin. alias: cf."], ["roll", "[dice]", "roll dice. alias: dice."], ["choose", "<a | b | c>", "choose one option. alias: pick."], ["rps", "<rock|paper|scissors>", "play rock, paper, scissors."], ["uwu", "<text>", "transform text into uwu style."], ["reverse", "<text>", "reverse text."], ["mock", "<text>", "alternate letter case."], ["clap", "<text>", "separate words with clap."], ["spacify", "<text>", "space out characters. alias: space."], ["emojify", "<text>", "convert letters to regional indicator emoji."], ["slap", "<user>", "send a slap action."], ["hug", "<user>", "send a hug action."], ["pat", "<user>", "send a pat action."], ["bonk", "<user>", "send a bonk action."], ["punch", "<user>", "send a punch action."], ["kiss", "<user>", "send a kiss action."], ["poke", "<user>", "send a poke action."], ["stare", "<user>", "send a stare action."], ["yeet", "<user>", "send a yeet action."], ["wave", "<user>", "send a wave action."], ["cry", "None", "send a cry action."], ["dance", "None", "send a dance action."],
  ]),
  ...group("Moderation", "Whitelist+", [
    ["kick", "<user>", "remove a member from the server."], ["ban", "<user> [reason]", "ban a member."], ["unban", "<user_id>", "remove a ban."], ["mute", "<user> <duration>", "time out a member."], ["unmute", "<user>", "remove a timeout."], ["timeout", "<user> <duration>", "time out a member."], ["untimeout", "<user>", "remove a timeout."], ["forcemute", "<user>", "keep a member muted across voice rejoins. alias: fm."], ["unforcemute", "<user>", "remove a force mute. alias: ufm."], ["forcemuted", "None", "list force muted members."], ["forcedeafen", "<user>", "keep a member deafened. alias: fdn."], ["unforcedeafen", "<user>", "remove a force deafen. alias: ufdn."], ["forcedeafened", "None", "list force deafened members."], ["forcedisconnect", "<user>", "bar a member from voice. aliases: fd, fdc."], ["unforcedisconnect", "<user>", "lift a voice ban. aliases: ufd, ufdc."], ["vcbanned", "None", "list members barred from voice."], ["shush", "<user>", "toggle message deletion for a member."], ["handle", "None", "toggle channel handling."], ["slowmode", "<seconds>", "set channel slowmode."], ["purge", "<amount>", "bulk delete messages. alias: c."], ["selfpurge", "<amount>", "delete your own recent messages."], ["nuke", "None", "recreate the current channel."], ["jail", "<user>", "jail a member."], ["unjail", "<user>", "release a member from jail."], ["strip", "<user>", "remove a member's roles."], ["restorerole", "<user>", "restore a member's saved roles."], ["shine", "None", "toggle channel highlighting."], ["role", "<user> <role>", "give a role to a member. alias: r."], ["unrole", "<user> <role>", "remove a role from a member."], ["roleall", "@role", "give a role to eligible members and report progress."], ["unroleall", "@role", "remove a role from eligible members and report progress."], ["roleall stop", "None", "request the running roleall job to stop."], ["unroleall stop", "None", "request the running unroleall job to stop."], ["role create", "<name> [color]", "create a role."], ["role delete", "<name>", "delete a role."], ["role edit", "<name> <color>", "edit a role color."], ["fn", "<user> <nickname>", "set a member's nickname."], ["ghostping", "<user>", "mention and delete a message."], ["emojisteal", "<emoji> [name]", "add an emoji from another server."], ["joinvc", "[channel]", "join a voice channel."], ["leavevc", "None", "leave voice."], ["drag", "<user...>", "drag members to your voice channel. alias: vc drag."], ["privatevc", "[users...]", "make a private voice channel."], ["privatevc allow", "<user...>", "allow users into a private voice channel."], ["snipe", "None", "show the last deleted message. alias: s."], ["clearsnipe", "None", "clear deleted message history. alias: cs."], ["banlist", "None", "list banned members."], ["history", "<user>", "show moderation history."], ["altcheck", "<user>", "check an account for alt signals."],
  ]),
  ...group("Aboveall", "Aboveall+", [
    ["hardban", "<user>", "permanently ban a member. alias: snap."], ["unhardban", "<user>", "remove a permanent ban. alias: unsnap."], ["ignore", "<user>", "ignore a member from moderation."], ["unignore", "<user>", "remove a member from ignored users."], ["whitelist", "<user>", "add a member to the whitelist."], ["unwhitelist", "<user>", "remove a member from the whitelist."], ["rlock", "<role>", "lock a role from changes."], ["autorole", "<role|off>", "set or disable automatic roles."], ["setjailrole", "<role>", "set the jail role."], ["clearstrikes", "<user>", "clear a member's strikes."], ["clearbanactions", "<user>", "clear a member's ban actions."], ["prefix", "<new_prefix>", "change the server prefix."], ["rolecheck", "None", "check role configuration."], ["customizebot", "<nickname|avatar|banner|bio> <value|reset>", "customize the bot profile."], ["welcome", "None", "show welcome settings."], ["welcome edit", "[message]", "change the welcome template."], ["welcome channel", "#channel", "set the welcome channel."], ["welcome preview", "None", "render a welcome test."], ["welcome variables", "None", "list welcome placeholders."], ["welcome on", "None", "enable welcome delivery."], ["welcome off", "None", "disable welcome delivery."], ["ticketpanel", "[#channel]", "post the open-ticket button."], ["ticketcategory", "<category>", "set where tickets are created."], ["ticketsuprole", "<@role|off>", "set or remove the ticket support role."], ["altcheck on", "None", "enable alt checking."], ["altcheck off", "None", "disable alt checking."], ["altcheck age", "<days>", "set the alt account age threshold."], ["altcheck autokick", "<on|off>", "toggle automatic alt kicks."], ["altcheck channel", "#channel", "set the alt check channel."], ["logs", "None", "show logging settings."],
  ]),
  ...group("Owner", "Owner", [
    ["addowner", "<user>", "add a server owner."], ["removeowner", "<user>", "remove a server owner."], ["aboveall", "<user>", "grant or remove aboveall access."], ["strikes", "[user]", "show strikes."], ["backup", "[name]", "create a server backup."], ["backup list", "None", "list server backups."], ["backup delete", "<name>", "delete a server backup."], ["backup load", "<name>", "load a server backup."], ["backup auto", "<on|off>", "toggle automatic backups."], ["gw create", "None", "create a giveaway."], ["gw end", "<id>", "end a giveaway."], ["gw cmds", "None", "show giveaway commands."], ["setup", "None", "configure the bot for this server."],
  ]),
  ...group("Panels", "VC owner / co-owner", [
    ["vc", "None", "show voice channel commands."], ["vc cmds", "None", "list voice channel commands."], ["vc create", "[name]", "create a voice channel you own."], ["vc claim", "#channel", "claim an unowned voice channel."], ["vc status", "[#channel]", "show activity and settings for a managed voice channel."], ["vc leaderboard", "None", "rank voice channels by recorded time."], ["vc team", "[#channel]", "show the owner, co-owners, and allowed users."], ["vc rename", "<name>", "rename a managed voice channel."], ["vc lock", "None", "lock a managed voice channel."], ["vc unlock", "None", "unlock a managed voice channel."], ["vc allow", "<user...>", "allow users into a managed voice channel."], ["vc unallow", "<user...>", "remove users from a managed voice channel."], ["vc whitelist", "<user...>", "whitelist users in a managed voice channel."], ["vc unwhitelist", "<user...>", "remove users from the voice whitelist."], ["vc limit", "<0-99>", "set the user limit."], ["vc disconnect", "<user...>", "disconnect users from the channel."], ["vc transfer", "<user>", "transfer channel ownership."], ["vc unclaim", "None", "remove your channel claim."], ["vc delete", "None", "delete a managed voice channel."], ["antinuke", "None", "view or configure anti-nuke protection."],
  ]),
  ...group("Panels", "Ticket support role or Aboveall+", [
    ["ticket claim", "None", "assign the current ticket to eligible staff."],
  ]),
]

export const TOTAL_COMMANDS = COMMANDS.length
export const UNIQUE_COMMANDS = COMMANDS.filter((command, index, commands) => commands.findIndex((item) => item.name === command.name) === index)
export const DISPLAY_COMMANDS = UNIQUE_COMMANDS
export const DISPLAY_CATEGORIES = CATEGORIES
